# Generated by Django 2.0.1 on 2018-02-05 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_feed', models.CharField(max_length=200)),
                ('uri', models.URLField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('uri', models.URLField(unique=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_hash', models.BinaryField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_mode', models.BooleanField(default=False)),
                ('deletion_pending', models.BooleanField(default=False)),
                ('feeds', models.ManyToManyField(blank=True, related_name='subscribers', to='reader.Feed')),
                ('read', models.ManyToManyField(blank=True, related_name='read_by', to='reader.Article')),
                ('stars', models.ManyToManyField(blank=True, related_name='stared_by', to='reader.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Feed'),
        ),
    ]
