# Generated by Django 2.0.1 on 2018-02-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='frequency_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
