# Generated by Django 2.0.6 on 2018-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20180614_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('feed', 'id_in_feed')},
        ),
    ]
