# Generated by Django 2.1.1 on 2018-09-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20180614_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_failure',
            field=models.TextField(blank=True),
        ),
    ]
