# Generated by Django 2.1.1 on 2018-09-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_feed_last_failure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_in_feed',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='article',
            name='uri',
            field=models.URLField(max_length=400),
        ),
    ]
