# Generated by Django 2.1.1 on 2018-09-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_auto_20180913_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(max_length=400)),
                ('title', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_in_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Article')),
            ],
        ),
    ]
