# Generated by Django 2.1.1 on 2018-09-18 11:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=100)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.ReaderProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('name', 'reader')},
        ),
    ]
