# Generated by Django 2.1.1 on 2018-09-28 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_auto_20180918_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.URLField(db_index=True, max_length=400, unique=True)),
                ('format', models.CharField(blank=True, default='', editable=False, max_length=8)),
                ('width', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('height', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('size_in_bytes', models.PositiveIntegerField(default=0, editable=False)),
                ('failure_reason', models.CharField(blank=True, default='', editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
