# Generated by Django 2.1.5 on 2019-01-05 14:44

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import reader.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_auto_20181001_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uri',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=100, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='uri',
            field=models.URLField(max_length=2048, unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), reader.validators.http_port_validator], verbose_name='Feed address'),
        ),
    ]
