# Generated by Django 2.2.3 on 2019-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0012_auto_20190105_1444'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'published_at'], name='reader_arti_feed_id_f173e6_idx'),
        ),
    ]
