# Generated by Django 2.2.4 on 2019-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0013_auto_20190707_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='size_in_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
