# Generated by Django 2.2.12 on 2020-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0014_auto_20190917_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_sync_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
