# Generated by Django 2.0.3 on 2018-03-12 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('um', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umprofile',
            name='items_per_page',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
