# Generated by Django 2.1.5 on 2019-01-05 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('um', '0002_remove_umprofile_night_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='umprofile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('fr-fr', 'Français')], default='en-us', max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='umprofile',
            name='items_per_page',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Items per page'),
        ),
    ]
